"""
GitHub PR creation and management.

Creates a structured PR body including:
- Link to the originating issue (``Closes #N``)
- Acceptance criteria as checkboxes
- QA report summary
- Model assignments used during generation
"""

from __future__ import annotations

import logging

import git

from devfactory.context import PipelineContext
from devfactory.github.client import gh
from devfactory.github.git_ops import _default_branch, _workspace_path

logger = logging.getLogger(__name__)

PR_LABEL = "devfactory"


def create_or_update_pr(ctx: PipelineContext) -> tuple[str, int]:
    """
    Create a PR for the feature branch, or update it if it already exists.

    Returns:
        Tuple of (pr_url, pr_number).
    """
    repo = gh.get_repo(ctx.issue.repo)

    # Detect default branch from local clone
    local_repo = git.Repo(_workspace_path(ctx))
    base = _default_branch(local_repo)

    # Check if PR already exists for this branch
    existing = list(repo.get_pulls(state="open", head=f"{ctx.repo_owner}:{ctx.branch_name}"))
    if existing:
        pr = existing[0]
        pr.edit(body=_build_pr_body(ctx))
        logger.info(f"[pr] updated existing PR #{pr.number}")
    else:
        # Ensure devfactory label exists
        _ensure_pr_label(repo)

        pr = repo.create_pull(
            title=f"[DevFactory] {ctx.issue.title}",
            body=_build_pr_body(ctx),
            head=ctx.branch_name,
            base=base,
            draft=False,
        )
        # Link to issue via label
        pr.add_to_labels(PR_LABEL)
        logger.info(f"[pr] created PR #{pr.number}: {pr.html_url}")

    return pr.html_url, pr.number


def _build_pr_body(ctx: PipelineContext) -> str:
    """Build a structured PR description."""
    spec = ctx.task_spec
    lines = [
        f"## {ctx.issue.title}",
        "",
        f"Closes #{ctx.issue.number}",
        "",
        "---",
        "",
        "### Summary",
        spec.summary if spec else "_No task spec available_",
        "",
    ]

    if spec and spec.acceptance_criteria:
        lines += ["### Acceptance Criteria", ""]
        for criterion in spec.acceptance_criteria:
            lines.append(f"- [ ] {criterion}")
        lines.append("")

    # QA summary
    if ctx.qa_report:
        lines += [
            "### QA Results",
            "",
            ctx.qa_report.summary,
            "",
        ]

    # Model assignments
    if ctx.model_assignments:
        lines += ["### Agent Models Used", ""]
        for role, model in ctx.model_assignments.items():
            lines.append(f"- **{role}**: `{model}`")
        lines.append("")

    lines += [
        "---",
        "_Generated by [DevFactory](https://github.com/devfactory) 🤖_",
    ]

    return "\n".join(lines)


def _ensure_pr_label(repo):
    existing = {l.name for l in repo.get_labels()}
    if PR_LABEL not in existing:
        try:
            repo.create_label(name=PR_LABEL, color="7057ff", description="Created by DevFactory")
        except Exception:
            pass
